set names 'utf8';
set session_replication_role = 'replica';

create table "clinics" ("id" uuid not null default gen_random_uuid(), "name" varchar(255) not null, "address" text not null, "phone" varchar(20) not null, "email" varchar(255) not null, "website" varchar(255) null, "logo_url" varchar(500) null, "description" text null, "working_hours" text null, "primary_color" varchar(7) not null default '#3B82F6', "secondary_color" varchar(7) not null default '#1F2937', "font_family" varchar(100) not null default 'Inter', "timezone" varchar(50) not null default 'Asia/Jakarta', "language" varchar(10) not null default 'id', "email_notifications" boolean not null default true, "sms_notifications" boolean not null default false, "push_notifications" boolean not null default false, "status" varchar(20) not null default 'pending', "is_active" boolean not null default true, "subscription_tier" varchar(20) not null default 'alpha', "subscription_expires" timestamptz(0) null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "clinics_pkey" primary key ("id"), constraint clinics_status_check check (status IN ('active', 'suspended', 'pending', 'inactive')), constraint clinics_subscription_tier_check check (subscription_tier IN ('alpha', 'beta', 'theta', 'delta')));

create table "clients" ("id" uuid not null default gen_random_uuid(), "clinic_id" uuid not null, "full_name" varchar(255) not null, "gender" varchar(10) not null, "birth_place" varchar(255) not null, "birth_date" timestamptz(0) not null, "religion" varchar(50) not null, "occupation" varchar(255) not null, "education" varchar(50) not null, "education_major" varchar(255) null, "address" text not null, "phone" varchar(20) not null, "email" varchar(255) null, "hobbies" text null, "marital_status" varchar(20) not null, "spouse_name" varchar(255) null, "relationship_with_spouse" varchar(20) null, "first_visit" boolean not null default true, "previous_visit_details" text null, "province" varchar(100) null, "emergency_contact_name" varchar(255) null, "emergency_contact_phone" varchar(20) null, "emergency_contact_relationship" varchar(100) null, "emergency_contact_address" text null, "is_minor" boolean not null default false, "school" varchar(255) null, "grade" varchar(50) null, "guardian_full_name" varchar(255) null, "guardian_relationship" varchar(50) null, "guardian_phone" varchar(20) null, "guardian_address" text null, "guardian_occupation" varchar(255) null, "guardian_marital_status" varchar(50) null, "guardian_legal_custody" boolean null, "guardian_custody_docs_attached" boolean null, "status" varchar(20) not null default 'new', "join_date" timestamptz(0) not null default CURRENT_DATE, "total_sessions" int not null default 0, "last_session_date" timestamptz(0) null, "progress" int not null default 0, "notes" text null, "name" varchar(255) null, "age" int null, "primary_issue" text null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "clients_pkey" primary key ("id"), constraint clients_progress_check check (progress >= 0 AND progress <= 100));

create table "registrations" ("id" uuid not null, "email" varchar(255) not null, "status" text check ("status" in ('started', 'clinic_data_submitted', 'documents_uploaded', 'payment_pending', 'payment_completed', 'completed', 'cancelled', 'expired')) not null default 'started', "current_step" text check ("current_step" in ('start', 'clinic_data', 'documents', 'payment', 'complete')) not null default 'start', "completed_steps" jsonb null, "clinic_data" jsonb null, "payment_data" jsonb null, "payment_status" text check ("payment_status" in ('pending', 'processing', 'completed', 'failed', 'cancelled')) not null default 'pending', "documents" jsonb null, "verification_code" varchar(255) null, "email_verified" boolean not null default false, "email_verified_at" timestamptz(0) null, "created_user_id" uuid null, "created_clinic_id" uuid null, "created_at" timestamptz(0) not null, "updated_at" timestamptz(0) not null, "completed_at" timestamptz(0) null, "expires_at" timestamptz(0) null, "metadata" jsonb null, constraint "registrations_pkey" primary key ("id"));
create index "registrations_email_index" on "registrations" ("email");
create index "registrations_created_at_index" on "registrations" ("created_at");
create index "registrations_status_index" on "registrations" ("status");

create table "users" ("id" uuid not null default gen_random_uuid(), "email" varchar(255) not null, "password_hash" varchar(255) not null, "email_verified" boolean not null default false, "email_verification_token" varchar(255) null, "email_verification_expires" timestamptz(0) null, "email_verified_at" timestamptz(0) null, "password_reset_token" varchar(255) null, "password_reset_expires" timestamptz(0) null, "avatar_url" varchar(500) null, "last_login" timestamptz(0) null, "is_active" boolean not null default true, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "users_pkey" primary key ("id"));
alter table "users" add constraint "users_email_unique" unique ("email");

create table "therapists" ("id" uuid not null default gen_random_uuid(), "clinic_id" uuid not null, "user_id" uuid not null, "full_name" varchar(255) not null, "phone" varchar(20) not null, "avatar_url" varchar(500) null, "license_number" varchar(100) not null, "license_type" varchar(50) not null, "years_of_experience" int not null default 0, "status" varchar(20) not null default 'pending_setup', "employment_type" varchar(20) not null, "join_date" timestamptz(0) not null, "max_clients" int not null default 10, "current_load" int not null default 0, "timezone" varchar(50) not null default 'Asia/Jakarta', "session_duration" int not null default 60, "break_between_sessions" int not null default 15, "max_sessions_per_day" int not null default 8, "working_days" jsonb not null default '[1,2,3,4,5]', "admin_notes" text null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "therapists_pkey" primary key ("id"));
alter table "therapists" add constraint "therapists_clinic_id_license_number_unique" unique ("clinic_id", "license_number");

create table "therapy_sessions" ("id" uuid not null default gen_random_uuid(), "client_id" uuid not null, "therapist_id" uuid not null, "session_number" int not null, "title" varchar(255) not null, "description" text null, "session_date" timestamptz(0) not null, "session_time" time(0) not null, "duration" int not null default 60, "status" varchar(20) not null default 'planned', "notes" text null, "techniques" jsonb null, "issues" jsonb null, "progress" text null, "ai_predictions" jsonb null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "therapy_sessions_pkey" primary key ("id"));

create table "therapist_specializations" ("id" uuid not null default gen_random_uuid(), "therapist_id" uuid not null, "specialization" varchar(100) not null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "therapist_specializations_pkey" primary key ("id"));
alter table "therapist_specializations" add constraint "therapist_specializations_therapist_id_specialization_unique" unique ("therapist_id", "specialization");

create table "consultations" ("id" uuid not null default gen_random_uuid(), "client_id" uuid not null, "therapist_id" uuid not null, "form_type" varchar(50) not null, "status" varchar(20) not null default 'draft', "session_date" timestamptz(0) not null, "session_duration" int not null, "consultation_notes" text null, "previous_therapy_experience" boolean not null default false, "previous_therapy_details" text null, "current_medications" boolean not null default false, "current_medications_details" text null, "primary_concern" text not null, "secondary_concerns" jsonb null, "symptom_severity" int null, "symptom_duration" varchar(100) null, "treatment_goals" jsonb null, "client_expectations" text null, "initial_assessment" text null, "recommended_treatment_plan" text null, "form_data" jsonb null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "consultations_pkey" primary key ("id"), constraint consultations_symptom_severity_check check (symptom_severity >= 1 AND symptom_severity <= 5));

create table "client_therapist_assignments" ("id" uuid not null default gen_random_uuid(), "client_id" uuid not null, "therapist_id" uuid not null, "assigned_date" timestamptz(0) not null default CURRENT_DATE, "assigned_by_id" uuid not null, "status" varchar(20) not null default 'active', "notes" text null, "end_date" timestamptz(0) null, "transfer_reason" text null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "client_therapist_assignments_pkey" primary key ("id"));
create index "client_therapist_assignments_client_id_therapist_id_status_index" on "client_therapist_assignments" ("client_id", "therapist_id", "status");

create table "client_status_transitions" ("id" uuid not null default gen_random_uuid(), "client_id" uuid not null, "from_status" varchar(20) null, "to_status" varchar(20) not null, "reason" text null, "notes" text null, "changed_by_id" uuid not null, "changed_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "previous_therapist_id" varchar(50) null, "new_therapist_id" varchar(50) null, constraint "client_status_transitions_pkey" primary key ("id"));
create index "client_status_transitions_from_status_to_status_index" on "client_status_transitions" ("from_status", "to_status");
create index "client_status_transitions_client_id_index" on "client_status_transitions" ("client_id");

create table "audit_logs" ("id" uuid not null default gen_random_uuid(), "user_id" uuid null, "action" varchar(100) not null, "entity_type" varchar(50) not null, "entity_id" uuid null, "old_values" jsonb null, "new_values" jsonb null, "ip_address" varchar(255) null, "user_agent" text null, "timestamp" timestamptz(0) not null default CURRENT_TIMESTAMP, constraint "audit_logs_pkey" primary key ("id"));

create table "user_profiles" ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null, "name" varchar(255) not null, "phone" varchar(20) null, "address" text null, "bio" text null, "avatar_url" varchar(500) null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "updated_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "userId" uuid not null, constraint "user_profiles_pkey" primary key ("id"));
alter table "user_profiles" add constraint "user_profiles_user_id_unique" unique ("user_id");
alter table "user_profiles" add constraint "user_profiles_userId_unique" unique ("userId");

create table "user_roles" ("id" uuid not null default gen_random_uuid(), "user_id" uuid not null, "role" varchar(50) not null, "clinic_id" uuid null, "created_at" timestamptz(0) not null default CURRENT_TIMESTAMP, "userId" uuid not null, "clinicId" uuid null, constraint "user_roles_pkey" primary key ("id"));
create index "user_roles_user_id_index" on "user_roles" ("user_id");
alter table "user_roles" add constraint "user_roles_user_id_role_clinic_id_unique" unique ("user_id", "role", "clinic_id");

alter table "clients" add constraint "clients_clinic_id_foreign" foreign key ("clinic_id") references "clinics" ("id") on update cascade on delete cascade;

alter table "therapists" add constraint "therapists_clinic_id_foreign" foreign key ("clinic_id") references "clinics" ("id") on update cascade on delete cascade;
alter table "therapists" add constraint "therapists_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade on delete cascade;

alter table "therapy_sessions" add constraint "therapy_sessions_client_id_foreign" foreign key ("client_id") references "clients" ("id") on update cascade on delete cascade;
alter table "therapy_sessions" add constraint "therapy_sessions_therapist_id_foreign" foreign key ("therapist_id") references "therapists" ("id") on update cascade on delete cascade;

alter table "therapist_specializations" add constraint "therapist_specializations_therapist_id_foreign" foreign key ("therapist_id") references "therapists" ("id") on update cascade on delete cascade;

alter table "consultations" add constraint "consultations_client_id_foreign" foreign key ("client_id") references "clients" ("id") on update cascade on delete cascade;
alter table "consultations" add constraint "consultations_therapist_id_foreign" foreign key ("therapist_id") references "therapists" ("id") on update cascade on delete cascade;

alter table "client_therapist_assignments" add constraint "client_therapist_assignments_client_id_foreign" foreign key ("client_id") references "clients" ("id") on update cascade on delete cascade;
alter table "client_therapist_assignments" add constraint "client_therapist_assignments_therapist_id_foreign" foreign key ("therapist_id") references "therapists" ("id") on update cascade on delete cascade;
alter table "client_therapist_assignments" add constraint "client_therapist_assignments_assigned_by_id_foreign" foreign key ("assigned_by_id") references "users" ("id") on update cascade;

alter table "client_status_transitions" add constraint "client_status_transitions_client_id_foreign" foreign key ("client_id") references "clients" ("id") on update cascade on delete cascade;
alter table "client_status_transitions" add constraint "client_status_transitions_changed_by_id_foreign" foreign key ("changed_by_id") references "users" ("id") on update cascade;

alter table "audit_logs" add constraint "audit_logs_user_id_foreign" foreign key ("user_id") references "users" ("id") on update cascade on delete set null;

alter table "user_profiles" add constraint "user_profiles_userId_foreign" foreign key ("userId") references "users" ("id") on update cascade;

alter table "user_roles" add constraint "user_roles_userId_foreign" foreign key ("userId") references "users" ("id") on update cascade;
alter table "user_roles" add constraint "user_roles_clinicId_foreign" foreign key ("clinicId") references "clinics" ("id") on update cascade on delete set null;

set session_replication_role = 'origin';